"""create_exchange_rates_stock_prices_crypto_prices_tables

Revision ID: 850b6dc1f31c
Revises: 
Create Date: 2025-11-20 01:56:45.342787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850b6dc1f31c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_prices_id'), 'crypto_prices', ['id'], unique=False)
    op.create_index('ix_crypto_prices_source_timestamp', 'crypto_prices', ['source', 'timestamp'], unique=False)
    op.create_index(op.f('ix_crypto_prices_symbol'), 'crypto_prices', ['symbol'], unique=False)
    op.create_index('ix_crypto_prices_symbol_timestamp', 'crypto_prices', ['symbol', 'timestamp'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_currency_pair'), 'exchange_rates', ['currency_pair'], unique=False)
    op.create_index('ix_exchange_rates_currency_timestamp', 'exchange_rates', ['currency_pair', 'timestamp'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_index('ix_exchange_rates_source_timestamp', 'exchange_rates', ['source', 'timestamp'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'ticker')
    )
    op.create_index(op.f('ix_stock_prices_id'), 'stock_prices', ['id'], unique=False)
    op.create_index('ix_stock_prices_sources_timestamp', 'stock_prices', ['source', 'timestamp'], unique=False)
    op.create_index(op.f('ix_stock_prices_ticker'), 'stock_prices', ['ticker'], unique=False)
    op.create_index('ix_stock_prices_ticker_timestamp', 'stock_prices', ['ticker', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_prices_ticker_timestamp', table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_ticker'), table_name='stock_prices')
    op.drop_index('ix_stock_prices_sources_timestamp', table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_id'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index('ix_exchange_rates_source_timestamp', table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index('ix_exchange_rates_currency_timestamp', table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_currency_pair'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index('ix_crypto_prices_symbol_timestamp', table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_symbol'), table_name='crypto_prices')
    op.drop_index('ix_crypto_prices_source_timestamp', table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_id'), table_name='crypto_prices')
    op.drop_table('crypto_prices')
    # ### end Alembic commands ###
